### PR TITLE
scala script to run flask locally

### PR DESCRIPTION
**Pull request by danbills**

### CODE REVIEW

**Comment by timperrett** [comment]
So I think you actually dont need this. You can start a local flask by simply doing `flask/re-start`, this loads the config file at `etc/development/flask/flask.dev.cfg`; does that work for you? :-)

**Comment by danbills** [comment]
In what context is the `flask/re-start` command issued?

**Comment by timperrett** [comment]
@danbills you can run it from the sbt prompt; its for local testing. It's not something you'd issue otherwise.

**Comment by timperrett** [comment]
@danbills just checking, did my previous make sense? want to qualify that this PR is redundant based on my previous comment, or do something about it if that doesnt answer it :-) Cheers!

**Comment by danbills** [comment]
@timperrett unfortunately I can't reproduce running `flask/re-start` from SBT prompt.  I'm sure I'm missing something simple.  Can you explain like I'm 5?

(This is indeed for local testing).

    sbt flask/re-start
    [error] Not a valid key: re-start (similar: re-start-args, reStartArgs, state)
    [error] flask/re-start

    sbt 'project flask' re-start
    [error] Not a valid command: re-start
    [error] Not a valid project ID: re-start
    [error] Expected ':' (if selecting a configuration)
    [error] Expected '::'
    [error] Not a valid key: re-start (similar: re-start-args, reStartArgs, state)

**Comment by timperrett** [comment]
@danbills my bad, forgot to add the settings :-) Just fixed it here: https://github.com/oncue/funnel/pull/36 - please pull and make sure that it works for you.

**Comment by danbills** [comment]
@timperrett The missing link! :)  Appreciated.

**Pull request closed without merging**
