### PR TITLE
Refactoring Elastic module to make it more testable and survive errors

### PR DESCRIPTION
**Pull request by neigor**
@timperrett @runarorama please review

Refactored `Elastic` object to move out `Dispatch` code. This simplifies test case creation (added several tests). Also cleaned up a little code around template creation. 

Real bug fix is in the `doPublish` code (lines 135-145). Previous code would retry but if problem is not gone after number of retries then exception will halt "writer" process. Reader will be fine though until buffer is filled. And then we never recover.

Let me know if my `Kliesli` code can be simplified, i am still learning how to use those efficiently.

### CODE REVIEW

**Comment by timperrett** [comment]
@neigor thanks for finding this -- im not sure about abstracting on the HTTP operations like this though, feels like it would probably be better to just have a function that returns the thing you want, without having to know about HTTP. Travis is saying the tests dont pass though, so probally take a look at that? On the whole, good set of changes and important bug fixes :-)

@stew @runarorama can you look at this too?

**Comment by neigor** [comment]
@timperrett I think i've fixed the test (it seem to pass before because error was swallowed? - see https://github.com/neigor/funnel/commit/45d682439b3267e45139cb8c8e5e3851e114a8f4) but build fails again for different reasons. How can we try to restart them?

**Comment by timperrett** [comment]
@neigor there's a restart button in the top right of the build; just restarted the 2.10 build and it passed. Verifying the 2.11 one and then we can merge. Thanks!

**Comment by neigor** [comment]
I probably do not have permissions => do not see it.

**Comment by timperrett** [comment]
@neigor ah interesting. didnt know that was a thing :-)

**Pull request merged**
